In [1]:
import numpy as np

In [2]:
a = np.asarray([1,2,3],dtype='float32')

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a)

[1. 2. 3.]


In [5]:
print(a.shape)

(3,)


In [6]:
b = np.array([[1,2,0],[3,4,0],[3,8,0]])
print(b)

[[1 2 0]
 [3 4 0]
 [3 8 0]]


In [7]:
b[1:,1:] = 100
print(b)

[[  1   2   0]
 [  3 100 100]
 [  3 100 100]]


In [8]:
six_identity = 6*np.eye(5,dtype='int32')
print(six_identity)

[[6 0 0 0 0]
 [0 6 0 0 0]
 [0 0 6 0 0]
 [0 0 0 6 0]
 [0 0 0 0 6]]


In [9]:
np.random.randint(10,20,(5,5))

array([[19, 11, 17, 18, 17],
       [10, 13, 13, 15, 19],
       [13, 10, 14, 12, 10],
       [16, 13, 12, 17, 10],
       [19, 10, 14, 18, 10]])

In [10]:
a2 = np.random.randint(10,20,(5,))

In [12]:
a1 = np.random.randint(0,10,(5,1))

In [13]:
print(a1)

[[6]
 [8]
 [1]
 [4]
 [8]]


In [15]:
print(a2)
print(np.max(a2))
print(np.min(a2))
print(np.sum(a2))
print(np.mean(a2))

[13 15 11 12 15]
15
11
66
13.2


In [16]:
np.exp?

In [19]:
a3 = np.random.randint(10,20,(5,5,6)) #tensor

In [20]:
a = np.random.randint(1,5,(3,4))
print(a)

[[2 3 2 1]
 [1 1 1 4]
 [3 1 4 4]]


In [21]:
b = a+5

In [22]:
c = b - a
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
l = np.array([1,2,3,5])
print(l+c)

[[ 6  7  8 10]
 [ 6  7  8 10]
 [ 6  7  8 10]]


In [24]:
l

array([1, 2, 3, 5])

In [25]:
l**2

array([ 1,  4,  9, 25], dtype=int32)

In [26]:
print(a)

[[2 3 2 1]
 [1 1 1 4]
 [3 1 4 4]]


In [27]:
b = np.array(a) #create a copy of a

In [28]:
b[0][0] = 20

In [29]:
print(b)

[[20  3  2  1]
 [ 1  1  1  4]
 [ 3  1  4  4]]


In [30]:
print(a)

[[2 3 2 1]
 [1 1 1 4]
 [3 1 4 4]]


In [31]:
c = np.vstack((a,b))

In [32]:
print(c)

[[ 2  3  2  1]
 [ 1  1  1  4]
 [ 3  1  4  4]
 [20  3  2  1]
 [ 1  1  1  4]
 [ 3  1  4  4]]


In [33]:
d = np.hstack((a,b))

In [34]:
print(d)

[[ 2  3  2  1 20  3  2  1]
 [ 1  1  1  4  1  1  1  4]
 [ 3  1  4  4  3  1  4  4]]


# Matplotlib

In [36]:
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'